import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Container } from "@/components/Container";
import { Navbar } from "@/components/Navbar/Navbar";
import { Footer } from "@/components/Footer/Footer";
import Cart from "@/components/Cart/Cart";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/store/useCart";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ThemeProvider } from "next-themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "300 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "zomrak.store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} light:bg-white dark:main-bg overflow-x-hidden font-medium ${geistMono.variable} font-geistSans antialiased`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          <ReactQueryProvider>
            <CartProvider>
              <Container>
                <Navbar />
                {children}
                <Footer />
                <Cart />
              </Container>
            </CartProvider>
          </ReactQueryProvider>

          <Toaster />
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
